/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leepood_bsdiff_tools_PatchTools */

#ifndef _Included_com_leepood_bsdiff_tools_PatchTools
#define _Included_com_leepood_bsdiff_tools_PatchTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leepood_bsdiff_tools_PatchTools
 * Method:    applay_patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_leepood_bsdiff_tools_PatchTools_applay_1patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
